<?php
/**
 * @category   Asm
 * @package    Asm_Search
 * @author     sunilnalawade15@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@g$
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace TEXT\Smsnotifications\Controller\Index;
use Magento\Framework\App\Action\Context;
use \TEXT\Smsnotifications\Helper\Data as Helper;

class Ordersmsflag extends \Magento\Framework\App\Action\Action
{
        
        protected $_helper;

    public function __construct(
        \Magento\Sales\Api\OrderRepositoryInterface $orderRepository,
            \Magento\Framework\Api\SearchCriteriaBuilder $searchCriteriaBuilder,
            \Magento\Framework\Api\SortOrderBuilder $sortBuilder,
            Helper $helper,
            Context $context
    ) {
          $this->orderRepository = $orderRepository;
              $this->searchCriteriaBuilder = $searchCriteriaBuilder;
              $this->sortBuilder = $sortBuilder;
              $this->_helper  = $helper;
        parent::__construct($context);
    }


    public function execute()
    {
            // print_r("okkkk");exit;
                //date_default_timezone_set('Asia/Kolkata'); 
                $time = time();
                $to = date('Y-m-d H:i:s', $time);
                $lastTime = $time - 300; // 60*60*24
                $from = date('Y-m-d H:i:s', $lastTime);
                // print_r("to:-".$to);
                // print_r("from:-".$from); exit;
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $OrderFactory = $objectManager->create('Magento\Sales\Model\ResourceModel\Order\CollectionFactory');
                $orderCollection = $OrderFactory->create()->addFieldToSelect(array('*'));
                $orderCollection->addFieldToFilter('created_at', ['lteq' => $to])->addFieldToFilter('created_at', ['gteq' => $from]);
                // print_r($orderCollection->getSelect()->__toString());exit; 
                $resource = $objectManager->get('\Magento\Framework\App\ResourceConnection');
                $connection = $resource->getConnection();
                $tableName = $resource->getTableName('order_sms_flag');
            
            $orderData = $orderCollection->getData();
            // print_r($orderData);exit;
 			if(count($orderData)){
                foreach($orderCollection as $order):
                    $sql = "SELECT * FROM ". $tableName ." WHERE order_id = ".$order->getId();
                    $result = $connection->fetchAll($sql);
                   if(!count($result)){
    			     $sqlnew = "INSERT INTO " . $tableName . "(order_id, order_increment_id, sms_flag) VALUES('" . $order->getId() . "','" . $order->getIncrementId() . "','" . '0' . "')";
                     $connection->query($sqlnew);
                     echo "--insert";
                   }
                endforeach;
            }
    }
}

