<?php
$helper = $this->helper('Lof\MarketPlace\Helper\Data');
?>
<div class="page-title">
  <div class="title_left">
    <h3><?php echo 'Message'; ?></h3>
  </div>
</div>
<div class="row">
  	<div class="col-md-12 col-sm-12 col-xs-12">
    	<div class="x_panel">
	      	<div class="x_title">
	        	<h2><?php echo 'All Message'; ?></h2>
	        	<div class="clearfix"></div>
	     	</div>
	      	<div class="x_content">
		        <table id="datatable" class="table table-striped table-bordered">
		          	<thead>
			          	<tr class="headings">
			          		<th class="hidden"> </th>
			                <th class="column-title"><?php echo __('Id');?> </th>
			                <th class="column-title"><?php echo __('Sender Name');?> </th>
			                <th class="column-title"><?php echo __('Sender Email');?> </th>
			                <th class="column-title"><?php echo __('Subject');?> </th>
			                <th class="column-title"><?php echo __('Description');?> </th>
			                <th class="column-title"><?php echo __('Read');?> </th>
			                <th class="column-title"><?php echo __('Status');?> </th>
			                <th class="column-title"><?php echo __('Created At'); ?> </th>
			                <th class="column-title no-link last"><span class="nobr"><?php echo __('Action'); ?></span>
			                </th>
			                <th class="bulk-actions" colspan="7">
			                  <a class="antoo" style="color:#fff; font-weight:500;"><?php echo __('Bulk Actions');?> ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
			                </th>
			          	</tr>
			        </thead>
			        <tbody>
		
				         <?php foreach ($this->getMessage()->setOrder('message_id', 'desc') as $key => $message) { 
				         	$read = $this->getUnreadMessage($message->getData('message_id')); 
				         	if(strtolower($read) == 'unread') {
				         		$class = 'red';
				         	} else {
				         		$class = 'green';
				         	} ?>
				         <tr>
				         	<td class="hidden"> </td>
				         	<td class=""><?php echo $message->getMessageId(); ?>  </td>
				         	<td class=""><?php echo $message->getSenderName(); ?>  </td>
				         	<td class=""><?php echo $message->getSenderEmail(); ?>  </td>
				         	<td class=""><?php echo $message->getSubject(); ?>  </td>
				         	<td class=""><?php echo $message->getDescription(); ?>  </td>
				         	<td class="<?php echo $class; ?>"><?php echo $read; ?>  </td>
				         	<td class=""><?php echo $helper->getStatus($message->getStatus()); ?>  </td>
				         	<td class=""><?php echo $message->getCreatedAt(); ?>  </td>
				         	<td class=" last"><a href="<?php echo $block->getUrl('catalog/message/view', ['view' => $message->getMessageId()]); ?>"><?php echo __('View'); ?></a>
				         </tr>
				         <?php } ?>
			        </tbody>    
		        </table>
	      	</div>
	    </div>  	
    </div>
 </div>

