<?php
/**
 * @category   Asm
 * @package    Asm_Search
 * @author     sunilnalawade15@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Asm\Search\Block;

use Magento\Framework\View\Element\Template\Context;
use Asm\Search\Model\SearchFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Search View block
 */
class SearchView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Search
     */
    protected $_search;
    public function __construct(
        Context $context,
        SearchFactory $search,
        FilterProvider $filterProvider
    ) {
        $this->_search = $search;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Asm Search Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $search = $this->_search->create();
        $singleData = $search->load($id);
        if($singleData->getSearchId() && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}