<?php
/**
 * @category   Asm
 * @package    Asm_Search
 * @author     sunilnalawade15@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Asm\Search\Block;

/**
 * Search content block
 */
class Search extends \Magento\Framework\View\Element\Template
{
    protected $_productCollectionFactory;
    protected $_sellerCollection;

    public function __construct(
        \Magento\Catalog\Model\ResourceModel\Product\CollectionFactory $productCollectionFactory,
        \Lof\MarketPlace\Model\Seller $sellerCollection,
        \Asm\Search\Model\Searchview $inRanageseller,
        \Magento\Framework\View\Element\Template\Context $context
    ) {
        $this->_productCollectionFactory = $productCollectionFactory; 
        $this->_sellerCollection = $sellerCollection;
        $this->_inRanageseller = $inRanageseller;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Product Search'));
        
        return parent::_prepareLayout();
    }

    public function searchResult()
    {
        $lat = $this->getRequest()->getParam('latitude');
        $lon = $this->getRequest()->getParam('longitude');
        $title = $this->getRequest()->getParam('title');
        // check current page
        $current_page = $this->getRequest()->getParam('current_page');
        if($current_page == ''){
            $current_page = 1;
        }else{
            $current_page = $this->getRequest()->getParam('current_page');
        }
        // Check page size
        $page_size = $this->getRequest()->getParam('page_size');
        if($page_size == ''){
            $page_size = 10;
        }else{
            $page_size = $this->getRequest()->getParam('page_size');
        }
        $productCollectionArray = array();
        $ranageSeller = $this->_inRanageseller->getInRangeSeller($lat, $lon);
        // filter prodcut collection as seller wise and name wise
        $arratAttributes = array();
         if($title){
            $collection = $this->_productCollectionFactory->create();
            $collection->addAttributeToSelect('*');
            $collection->addFieldToFilter('seller_id', array('in' => $ranageSeller));
            $collection->addAttributeToSort('price', 'asc');
            $collection->addFieldToFilter([['attribute' => 'name', 'like' => '%'.$title.'%']]);
            $collection->setCurPage($current_page)->setPageSize($page_size);
            foreach ($collection as $product){
                $productCollectionArray[$product->getId()] = $product->getData();
            } 
         //print_r($productCollectionArray);exit;
         }else{
             $collection = '';
         }

         if($productCollectionArray){
            $data = array('status' => 1,'message' => 'Search result','product_collection' => $productCollectionArray);
        }else{
            $data = array('status' => 0,'message' => 'No Search result','product_collection' => array());
        }

       // echo '<pre>';print_r($data);exit;
        echo json_encode($data);die;

         //return $collection;
    }
    public function searchTeam()
    {
        $title = $this->getRequest()->getParam('title');
        return $title;
    }
    public function getToolbarHtml()
    {
        //return $this->getChildHtml('toolbar');
         include ($this->getTemplateFile('toolbar.phtml'));
        //print_r("Hrerer");
    }
}
