<?php
/**
 * @category   Asm
 * @package    Asm_Search
 * @author     sunilnalawade15@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Asm\Search\Block;

use Magento\Framework\View\Element\Template\Context;
use Asm\Search\Model\SearchFactory;
/**
 * Search List block
 */
class SearchListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Search
     */
    protected $_search;
    public function __construct(
        Context $context,
        SearchFactory $search
    ) {
        $this->_search = $search;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Asm Search Module List Page'));
        
        if ($this->getSearchCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'asm.search.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getSearchCollection()
            );
            $this->setChild('pager', $pager);
            $this->getSearchCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getSearchCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $search = $this->_search->create();
        $collection = $search->getCollection();
        $collection->addFieldToFilter('status','1');
        //$search->setOrder('search_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}