<?php
$_sellerCollection = $block->getSellerCollection();
$_helper = $this->helper('Lof\MarketPlace\Helper\Data');
$title = $this->getConfig('seller_block/title');
$blockId = rand().time();

// Boostrap Carousel
$itemsperpage = (int)$this->getConfig('seller_block/item_per_page',6);
$lg_column_item = (int)$this->getConfig('seller_block/lg_column_item',6);
$md_column_item = (int)$this->getConfig('seller_block/md_column_item',6);
$sm_column_item = (int)$this->getConfig('seller_block/sm_column_item',6);
$xs_column_item = (int)$this->getConfig('seller_block/xs_column_item',6);

$lg_column = 12/$lg_column_item;
$md_column = 12/$md_column_item;
$sm_column = 12/$sm_column_item;
$xs_column = 12/$xs_column_item;

$show_seller_name = $this->getConfig('seller_block/show_seller_name');
$addition_class = $this->getConfig('seller_block/addition_class');
$interval = $this->getConfig('seller_block/interval',1000);
$auto_play = $this->getConfig('seller_block/auto_play');
$speed = $this->getConfig('seller_block/speed');
$dots = $this->getConfig('seller_block/dots',true);
$nav = $this->getConfig('seller_block/nav',true);
$nav_prev = $this->getConfig('seller_block/nav_prev');
$nav_next = $this->getConfig('seller_block/nav_next');

?>
<?php if ( $_sellerCollection->count() ){ ?>
<?php
$total = $_sellerCollection->getSize();
$totalPage = '';
if($total%$itemsperpage == 0){
	$totalPage = $total/$itemsperpage;
}else{
	$totalPage = floor($total/$itemsperpage)+1;
}
$pretext                = $_helper->filter($this->getConfig('seller_block/pretext'));
?>
<div class="block widget lof-widget seller-widget <?php echo $addition_class?$addition_class:'' ?>">
	<?php if($title){ ?>
	<div class="block-title">
		<strong><?php echo $title ?></strong>
	</div>
	<?php } ?>
	<?php if($pretext!=''){ ?>
	<div class="pretext-html"><?php echo $pretext ?></div>
	<?php } ?>
	<div id="productcarousel-<?php echo $blockId ?>" class="block-content carousel slide" data-ride="carousel" data-interval="<?php echo $interval?$interval:"false"; ?>">
		<!-- Indicators -->
		<?php if($dots && $totalPage>0){ ?>
		<ol class="carousel-indicators">
			<?php for ($i=0; $i < $totalPage ; $i++) { ?>
			<li data-target="#productcarousel-<?php echo $blockId ?>" data-slide-to="<?php echo $i ?>"></li>
			<?php } ?>
		</ol>
		<?php } ?>
		<!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox">
			<?php
			$i = 1;
			$x = 0;
			?>
			<?php foreach ($_sellerCollection as $_seller) { ?>
			<?php if( $itemsperpage == 1 || $i % $itemsperpage == 1){ ?>
			<div class="item <?php if($i==1){ ?>active<?php } ?>">
				<?php } ?>
				<?php if( $lg_column_item == 1 || $x%$lg_column_item == 0 || $x%$itemsperpage == 0){ ?>
				<div class="row">
					<?php } ?>
					<div class="col-lg-<?php echo $lg_column ?> col-md-<?php echo $md_column ?> col-sm-<?php echo $sm_column ?> col-xs-<?php echo $xs_column ?>">
						<div class="seller-item">
							<div class="seller-image"><a href="<?php echo $_seller->getUrl(); ?>" title="<?php echo $_seller->getName(); ?>"><img src="<?php echo $_seller->getThumbnailUrl(); ?>" alt="<?php echo $_seller->getName(); ?>"/></a></div>
							<?php if($show_seller_name){ ?>
							<div class="seller-name"><a href="<?php echo $_seller->getUrl(); ?>" title="<?php echo $_seller->getName(); ?>"><?php echo $_seller->getName() ?></a></div>
							<?php } ?>
						</div>
					</div>
					<?php if( $lg_column_item == 1 || ($x+1)%$lg_column_item == 0 || $i == $total || ($x>0 && ($x+1)%$itemsperpage == 0) ) {  ?>
				</div>
				<?php } ?>
				<?php if( $itemsperpage == 1 || ($i+1)%$itemsperpage == 1 || $i == $total ) { $x = -1; ?>
			</div>
			<?php } ?>
			<?php $i++; $x++; ?>
			<?php } ?>
		</div>
		<?php if($nav && $total>$xs_column_item){ ?>
		<div class="carousel-controls">
			<a class="left carousel-control" href="#productcarousel-<?php echo $blockId ?>" role="button" data-slide="prev"><?php echo $nav_prev?$nav_prev:'Previous'); ?></a>
			<a class="right carousel-control" href="#productcarousel-<?php echo $blockId ?>" role="button" data-slide="next"><?php echo $nav_next?$nav_next:'Next'; ?></a>
		</div>
		<?php } ?>
	</div>
</div>
<?php } ?>
<script type="text/javascript">
	require([<?php if($this->helper("Lof\All\Helper\Data")->getConfig("enable_bootstrap_js")): ?>
		"Lof_All/lib/bootstrap/js/bootstrap.min",
	<?php endif; ?>
		], function () {});
</script>