<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
	<div class="block-title">
		<strong id="block-new-customer-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('New Kirana') ?></strong>
	</div>
	<div class="block-content" aria-labelledby="block-new-customer-heading">
		<p><?php /* @escapeNotVerified */ echo __('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.') ?></p>
		<div class="actions-toolbar">
			<div class="primary">
				<a
					href="<?php /* @escapeNotVerified */ echo  $block->getUrl('lofmarketplace/seller/create') ?>"
					class="action create primary"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></a>
			</div>
		</div>
	</div>
</div>
<?php endif; ?>