<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Magento\Backend\Block\Widget\Button\SplitButton */
?>

<div <?php echo $block->getAttributesHtml(); ?>>
    <button <?php echo $block->getButtonAttributesHtml(); ?>>
        <span><?php echo $block->escapeHtml($block->getLabel()); ?></span>
    </button>
    <?php if ($block->hasSplit()): ?>
        <button <?php echo $block->getToggleAttributesHtml() ?>>
            <span class="caret"></span>
            <span class="sr-only">Select</span>
        </button>

        <?php if (!$block->getDisabled()): ?>
            <ul class="dropdown-menu" role="menu" <?php /* @escapeNotVerified */ echo $block->getUiId("dropdown-menu"); ?>>
                <?php foreach ($block->getOptions() as $key => $option): ?>
                <li>
                    <a href="#" <?php echo $block->getOptionAttributesHtml($key, $option); ?>>
                        <?php echo $block->escapeHtml($option['label']); ?>
                    </a>
                    <?php if (isset($option['hint'])): ?>
                    <div class="tooltip" <?php /* @escapeNotVerified */ echo $block->getUiId('item', $key, 'tooltip'); ?>>
                        <a href="<?php echo $block->escapeHtml($option['hint']['href']) ?>" class="help">
                            <?php echo $block->escapeHtml($option['hint']['label']) ?>
                        </a>
                    </div>
                    <?php endif; ?>
                </li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
    <?php endif; ?>
</div>
<script>
require(['jquery'], function($){
        $('.actions-split')
            .on('click.splitDefault', '.action-default', function() {
                $(this).siblings('.dropdown-menu').find('.item-default').trigger('click');
            });
});
</script>
<?php /*?>
<div class="btn-group">
    <button type="button" class="btn btn-default">Action</button>
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
        <span class="sr-only">Toggle Dropdown</span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><a href="#">Action</a></li>
        <li><a href="#">Another action</a></li>
        <li><a href="#">Something else here</a></li>
        <li class="divider"></li>
        <li><a href="#">Separated link</a></li>
    </ul>
</div>


*/?>