<?php
/**
 * @category   Asm
 * @package    Asm_Search
 * @author     sunilnalawade15@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Asm\Search\Controller\Index;

use Magento\Framework\App\Action\Context;
use Asm\Search\Model\SearchFactory;

class Save extends \Magento\Framework\App\Action\Action
{
	/**
     * @var Search
     */
    protected $_search;

    public function __construct(
		Context $context,
        SearchFactory $search
    ) {
        $this->_search = $search;
        parent::__construct($context);
    }
	public function execute()
    {
        $data = $this->getRequest()->getParams();
    	$search = $this->_search->create();
        $search->setData($data);
        if($search->save()){
            $this->messageManager->addSuccessMessage(__('You saved the data.'));
        }else{
            $this->messageManager->addErrorMessage(__('Data was not saved.'));
        }
        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('search/index/index');
        return $resultRedirect;
    }
}
