<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
	<div class="block-title">
		<strong id="block-new-customer-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('New Kirana') ?></strong>
	</div>
	<div class="block-content" aria-labelledby="block-new-customer-heading">
		<p><?php /* @escapeNotVerified */ echo __('Turn in to a kirana today and enjoy some incredible benefits like adding logo to your profile page for better branding, setting up multiple products to improve conversions, etc.') ?></p>
		<div class="actions-toolbar">
			<div class="primary">
				<!-- <a
					href="<?php /* @escapeNotVerified */ echo  $block->getUrl('lofmarketplace/seller/create') ?>"
					class="action create primary"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></a> -->

					<a
					href="<?php /* @escapeNotVerified */ echo  $block->getUrl('customer/account/create/') ?>"
					class="action create primary"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></a>
			</div>
		</div>
	</div>
</div>
<?php endif; ?>