<div class="page-title">
  <div class="title_left">
    <h3><?php echo 'Transaction Amount '; ?></h3>
  </div>
</div>
<div class="row">
  	<div class="col-md-12 col-sm-12 col-xs-12">
    	<div class="x_panel">
	      	<div class="x_title">
	        	<h2><?php echo 'Table Transaction Amount '; ?></h2>
	        	<div class="clearfix"></div>
	     	</div>
	      	<div class="x_content">
		        <table id="datatable" class="table table-striped table-bordered amount-transaction">
		          	<thead>
			          	<tr class="headings">
			          		<th class="hidden"></th>
			                <th class="column-title"><?php echo __('Id');?> </th>
			                <th class="column-title"><?php echo __('Amount');?> </th>
			                <th class="column-title"><?php echo __('Seller Blance');?> </th>
			                <th class="column-title"><?php echo __('Description');?> </th>
			                <th class="column-title"><?php echo __('Created At'); ?> </th>
			   
			          	</tr>
			        </thead>
			        <tbody>
			        <?php foreach ($this->getAmounttransaction()->setOrder('transaction_id','desc') as $key => $amount) {
			        if($amount->getData('amount') >=0) {
			        	$class = 'amount';
			        } else {
			        	$class = 'refund';
			        }	
			         ?>
						<tr class="even pointer">
							<td class="hidden"></td>
			                <td class=" "><?php echo $amount->getData('transaction_id'); ?></td>
			                <td class="<?php echo $class;?>"><?php echo $amount->getData('amount'); ?></td>
			                <td class=" "><?php echo $amount->getData('balance'); ?></i></td>
			                <td class=" "><?php echo $amount->getData('description'); ?></td>
			                <td class=" "><?php echo $amount->getData('created_at'); ?></td>
						</tr>
			        <?php } ?>  

			        </tbody>    
		        </table>
	      	</div>
	    </div>  	
    </div>
 </div>

