<div class="page-title">
  <div class="title_left">
    <h3><?php echo 'Invoice'; ?></h3>
  </div>
</div>
<div class="row">
  	<div class="col-md-12 col-sm-12 col-xs-12">
    	<div class="x_panel">
	      	<div class="x_title">
	        	<h2><?php echo 'Table Invoice'; ?></h2>
	        	<div class="clearfix"></div>
	     	</div>
	      	<div class="x_content">
		        <table id="datatable" class="table table-striped table-bordered">
		          	<thead>
			          	<tr class="headings">
			          		<th class="hidden"></th>
			                <th class="column-title"><?php echo __('Invoice');?> </th>
			                <th class="column-title"><?php echo __('Invoice Date');?> </th>
			                <th class="column-title"><?php echo __('Order');?> </th>
			                <th class="column-title"><?php echo __('Bill to Name');?> </th>
			                <th class="column-title"><?php echo __('Status');?> </th>
			                <th class="column-title"><?php echo __('Grand Total (Base)'); ?> </th>
			                <th class="column-title"><?php echo __('Grand Total (Purchased)'); ?> </th>
			                <th class="column-title no-link last"><span class="nobr"><?php echo __('Action'); ?></span>
			                </th>
			                <th class="bulk-actions" colspan="7">
			                  <a class="antoo" style="color:#fff; font-weight:500;"><?php echo __('Bulk Actions');?> ( <span class="action-cnt"> </span> ) <i class="fa fa-chevron-down"></i></a>
			                </th>
			          	</tr>
			        </thead>
			        <tbody>
			        <?php foreach ($this->getInvoiceCollection()->setOrder('order_id', 'desc')  as $key => $invoice) {
			        	
			         ?>
						<tr class="even pointer">
							<td class="hidden"></td>
			                <td class=" "><?php echo $invoice->getData('invoice_id'); ?></td>
			                <td class=" "><?php echo $invoice->getData('created_at'); ?></td>
			                <td class=" "><?php echo $invoice->getData('seller_order_id'); ?></i></td>
			                <td class=" "><?php echo $invoice->getData('billing_name'); ?></td>
			                <td class=" "><?php echo $this->getStatus($invoice->getData('state')); ?></td>
			                <td class="a-right a-right "><?php echo $this->getPriceFomat($invoice->getData('base_grand_total'),$invoice->getData('base_currency_code')); ?></td>
			                <td class="a-right a-right "><?php echo $this->getPriceFomat($invoice->getData('grand_total'),$invoice->getData('base_currency_code')); ?></td>
			                <td class=" last"><a href="<?php echo $block->getUrl('catalog/sales/invoiceview', ['view' => $invoice->getData('invoice_id')]); ?>"><?php echo __('View'); ?></a>
			                </td>
						</tr>
			        <?php } ?>  

			        </tbody>    
		        </table>
	      	</div>
	    </div>  	
    </div>
 </div>

