<script>

</script>
<?php
$val=0;
$edit = $this->getBuyXgetFixed();

if($edit['0']['customer_group']!= '')
               {
               $csg = $edit['0']['customer_group'];
               $arr_csg = explode(",",$csg);
            }else{
                $arr_csg = '';
            }
//logger
$writer = new \Zend\Log\Writer\Stream(BP . '/var/log/test.log');
 $logger = new \Zend\Log\Logger(); $logger->addWriter($writer);
  $logger->info($edit);
?>

    <p><?php    $customer_group = $block->getCustomerGroups(); 
                //print_r($customer_group);?> 
    </p>



<form id="buy_and_get_product" align="center">

    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ //echo __('Test Form') ?></span></legend><br>
        <div class="field required">
            <div class="control mb-20">
                <span type="" class="text-label">Buy Product
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <span><input type="text" id="buy_product" value="<?php echo  $edit['0']['buy_product']; ?>"  required name="number" class="input-text" placeholder="Enter Product">
                <input type='hidden' id="post_id" name="post_id" value="<?php echo  $edit['0']['post_id']; ?>"/>
    
                <div style="display: none;"></div></span>
            </div><br>

            <div class="control mb-20">
                <span type="" type="" class="buy_prdt text-label">Quantity
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <span class="quantity"><input type="number" id="quantity" value="<?php echo  $edit['0']['quantity']; ?>" required name="number" class="input-text" placeholder="Enter Quantity">
                <div  class="quantity" style="display: none;"></div></span>
            </div><br>

            <div class="control mb-20">
                <span type="" class="buy_prdt text-label">Fixed Price
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <span class="fixed_price"><input type="decimal" id="fixed_price" value="<?php echo  $edit['0']['fixed_price']; ?>" required name="number" class="input-text" placeholder="Enter Price">
                <div  style="display: none;"></div></span>
            </div><br>
            <div class="control mb-20">
                <span type="" class="buy_prdt  text-label">Name
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <span class="priority">
                <input type="text" id="name"  value="<?php echo  $edit['0']['name']; ?>" required class="input-text" placeholder="Enter Name">
                <div  style="display: none;"></div></span>
            </div><br>

            <div class="control mb-20">
                <span type="" class="buy_prdt  text-label">Store Id
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <span class="priority">
                <input type="text" id="store_id" required class="input-text"  value="<?php echo  $edit['0']['store_id']; ?>"   placeholder="Enter Store Id">
                <!-- value="<?php //echo  $edit['0']['store_id']; ?>" -->
               
                <div  style="display: none;"></div></span>
            </div><br>

            <div class="control mb-20">
                <span type="" class="buy_prdt text-label">Priority
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <span class="priority">
                <input id="priority" type="number" required value="<?php echo  $edit['0']['priority']; ?>" >
                <div  style="display: none;"></div></span>
            </div><br>

            <div class="control mb-20">
                <span type="" class="buy_prdt text-label">Status
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <span class="status">
                <select id="status">
                    <option value="1" <?php if(($edit['0']['status'])==1){ echo 'selected'; } ?>>Enabled</option>
                    <option value="0" <?php if(($edit['0']['status'])==0){ echo 'selected'; } ?>>Disabled</option>
                </select>
                <div  style="display: none;"></div></span>
            </div><br>

            

 
            <div class="control-offer-from mb-20">
                <span class="text-label">Offer From
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <!-- <input type="text" id="datepicker1" name="datepicker1" /> -->
                <input type="text" id="fromdate_offer" value="<?php echo  $edit['0']['offer_from']; ?>" required name="fromdate_offer">
                <div class="from_date" style="display: none;"></div>
            </div><br>
             
            <div class="control-offer-to mb-20">
                <span class="text-label">Offer To
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <input type="text" id="todate_offer" value="<?php echo  $edit['0']['offer_to']; ?>" required class="end_date" name="todate_offer">
                <div class="to_date" style="display: none;"></div>
            </div><br>
            
            <div class="control-offer-to mb-20">
                <span class="text-label">Select Group
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <select class="selectpicker" multiple data-live-search="true" required>
                  <?php foreach ($customer_group as $key => $value): ?>
                       <?php if($arr_csg != ''){?>
                       <option <?php foreach ($arr_csg as $key => $res) {
                           # code...
                           if($value['value']==$res){
                               echo 'selected';
                           }
                           else{
                               echo '';
                               }
                       } ?>
                       
                       value="<?php echo $value['value']; ?>"><?php echo $value['label']; ?></option>
                       <?php }else{
                       ?>
                       <option value="<?php echo $value['value']; ?>" ><?php echo $value['label']; ?></option>

                       <?php
                       } ?>
                       <?php endforeach; ?>               
               </select>
                <div class="select_group" style="display: none;"></div>
            </div><br>

        </div>
    </fieldset>
    <br>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="" class="primary btnfixed" title="<?php echo __('Submit') ?>">
            <span><?php echo __('Submit') ?></span>
            </button> 

        </div>
    </div>

</form>

<style>
    /* .mb-20{margin-bottom: 20px;}
    .input-fields{text-align: left}
    .input-text{width: 100%;}
    #priority{
        width: 100%;
        height: 40px;
        border-color: #d3d3d3;
    }
    .text-label{
        text-align: right;
        line-height: 25px;
        padding-right: 20px;
    }
    .flex{
        display: -webkit-flex;
        display: -moz-flex;
        display: -ms-flex;
        display: flex;
        justify-content: space-around;
        margin-bottom: 15px;
    }
    .add-fields{
        width: 100px;
        padding: 10px;
        font-weight: 600;
        color: #514943 !important;
        border: 1px solid #adadad;
        background-color: #e3e3e3;
        text-transform: uppercase;
        text-decoration: none !important;
    }
    input{
        padding:10px 30px;
        border: 1px solid #d3d3d3;
    }
    .required-field{
        color: #e02b27;
        margin-left: 5px;
        font-size:1.2rem;
    } */
</style>