<script>

</script>
<?php
$val=0;
$edit = $this->getBuyXXXgetY();

if($edit['0']['customer_group']!= '')
               {
               $csg = $edit['0']['customer_group'];
               $arr_csg = explode(",",$csg);
                }
                else{
                    $arr_csg = '';
                }
?>

    <p><?php    $customer_group = $block->getCustomerGroups(); 
                //print_r($customer_group);?> 
    </p>



<form id="buy_and_get_product" align="center">

    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ //echo __('Test Form') ?></span></legend><br>
        <div class="field required">
            
        <div class="control mb-20">
                <span type="" class="text-label">Base Subtotal
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <span class="buy_product"><input type="decimal" id="subtotal" value="<?php echo  $edit['0']['subtotal']; ?>" required name="number" class="input-text" placeholder="Enter Price">
                <input type='hidden' id="post_id" name="post_id" value="<?php echo  $edit['0']['post_id']; ?>"/>
    
                <div  style="display: none;"></div></span>
            </div><br>
            
            <div class="control mb-20">
                <span type="" class="buy_prdt text-label">Free Product
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <span><input type="text" id="get_product" value="<?php echo  $edit['0']['get_product']; ?>" required name="number" class="input-text" placeholder="Enter Product">
                <div class="buy-btn-create" style="display: none;"></div></span>
            </div><br>

            <div class="control mb-20">
                <span type="" class="buy_prdt text-label">Name
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <span><input type="text" id="name" value="<?php echo  $edit['0']['name']; ?>" required name="number" class="input-text" placeholder="Enter name">
                <div class="quantity" style="display: none;"></div></span>
            </div><br>

            <div class="control mb-20">
                <span type="" class="buy_prdt text-label">Store Id
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <span><input type="number" id="store_id"  value="<?php echo  $edit['0']['store_id']; ?>"  required name="number" class="input-text" placeholder="Enter Store Id">
                <div class="quantity" style="display: none;"></div></span>
            </div><br>



            <div class="control mb-20">
                <span type="" class="buy_prdt text-label">Product Quantity
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <span><input type="number" id="quantity" value="<?php echo  $edit['0']['quantity']; ?>" required name="number" class="input-text" placeholder="Enter Product Quantity">
                <div class="quantity" style="display: none;"></div></span>
            </div><br>

            <div class="control mb-20">
                <span type="" class="buy_prdt text-label">Priority
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <span class="priority">
                <input type="number"  id="priority" value="<?php echo  $edit['0']['priority']; ?>" required>
                <div  style="display: none;"></div></span>
            </div><br>

            <div class="control mb-20">
                <span type="" class="buy_prdt text-label">Status
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <span class="status">
                <select id="status">
                    <option value="1" <?php if(($edit['0']['status'])==1){ echo 'selected'; } ?>>Enabled</option>
                    <option value="0" <?php if(($edit['0']['status'])==0){ echo 'selected'; } ?>>Disabled</option>
                </select>
                <div  style="display: none;"></div></span>
            </div><br>
 
            <div class="control-offer-from mb-20">
                <span class="text-label">Offer From
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <!-- <input type="text" id="datepicker1" name="datepicker1" /> -->
                <input type="text" id="fromdate_offer" name="fromdate_offer" value="<?php echo  $edit['0']['offer_from']; ?>" required>
                <div class="from_date" style="display: none;"></div>
            </div><br>
             
            <div class="control-offer-to mb-20">
                <span class="text-label">Offer To
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <input type="text" id="todate_offer" value="<?php echo  $edit['0']['offer_to']; ?>" class="end_date" name="todate_offer" required>
                <div class="to_date" style="display: none;"></div>
            </div><br>
            
            <div class="control-offer-to mb-20">
                <span class="text-label">Select Group
                    <span style="margin-left: 5px;color: #e02b27;font-size:1.2rem">*</span>
                </span>
                <select class="selectpicker" multiple data-live-search="true" required>
                  <?php foreach ($customer_group as $key => $value): ?>
                       <?php if($arr_csg != ''){?>
                       <option <?php foreach ($arr_csg as $key => $res) {
                           # code...
                           if($value['value']==$res){
                               echo 'selected';
                           }
                           else{
                               echo '';
                               }
                       } ?>
                       
                       value="<?php echo $value['value']; ?>"><?php echo $value['label']; ?></option>
                       <?php }else{
                       ?>
                       <option value="<?php echo $value['value']; ?>"><?php echo $value['label']; ?></option>

                       <?php
                       } ?>
                       <?php endforeach; ?>               
               </select>
                <div class="select_group" style="display: none;"></div>
            </div><br>

        </div>
    </fieldset>
    <br>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="" class="primary btnworth" title="<?php echo __('Submit') ?>">
            <span><?php echo __('Submit') ?></span>
            </button> 

        </div>
    </div>

</form>
