<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$welcomeMessage = $block->getWelcome();
$customerSession = $objectManager->create('Magento\Framework\Session\SessionManagerInterface');
$sessionFullAdd = $customerSession->getFulladdress();
// print_r($sessionFullAdd);exit;
?>
<?php if(isset($sessionFullAdd)){ ?>
<li class="pull-left address-header"><span><strong>Current location:</strong></span> <?php if(isset($sessionFullAdd)){echo $sessionFullAdd;} ?> <a href="javascript:void(0)" class="change-location"><strong><u>Change</u></strong></a></li> 
<?php } ?>
<?php switch ($block->getShowPart()):
    case 'welcome': ?>
        <li class="greet welcome" data-bind="scope: 'customer'">
            <!-- ko if: customer().fullname  -->
            <span data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().fullname)">
            </span>
            <!-- /ko -->
            <!-- ko ifnot: customer().fullname  -->
            <span data-bind='html:"<?= $block->escapeHtml($welcomeMessage) ?>"'></span>
            <?= $block->getBlockHtml('header.additional') ?>
            <!-- /ko -->
        </li>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
    <?php break; ?>

    <?php case 'other': ?>
        <?= $block->getChildHtml() ?>
    <?php break; ?>

<?php endswitch; ?>
<style type="text/css">
/*.address-header {
    margin-right: 190px !important;
}*/
</style>
