<?php
$_sellerCollection = $block->getCollection();
$show_seller_name = $this->getConfig('seller_list_page/show_seller_name');
?>
<?php if ( $_sellerCollection->count() ){ ?>
<?php $total = $_sellerCollection->getSize(); ?>
<div class="sellerlist">
	<div class="block-content">
		<?php foreach ($_sellerCollection as $_seller) { ?>
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="seller-item">
				<div class="seller-image"><a href="<?php echo $_seller->getUrl(); ?>" title="<?php echo $_seller->getName(); ?>"><img src="<?php echo $_seller->getThumbnailUrl(); ?>" alt="<?php echo $_seller->getName(); ?>"/></a></div>
				<?php if($show_seller_name){ ?>
				<div class="seller-name"><a href="<?php echo $_seller->getUrl(); ?>" title="<?php echo $_seller->getName(); ?>"><?php echo $_seller->getName() ?></a></div>
				<?php } ?>
			</div>
		</div>
		<?php } ?>
	</div>
	<div class="seller-toolbar">
		<?php echo $block->getChildHtml('toolbar'); ?>
	</div>
</div>
<?php }else{ ?>
<div class="message info empty"><div><?php echo __('We can\'t find seller matching the selection.'); ?></div></div>
<?php } ?>