<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $element \Magento\Framework\Data\Form\Element\Fieldset */
$element = $block->getElement();
$containerId = $element->getFieldsetContainerId();
$id = $element->getHtmlId();
$isCollapsable = $element->getCollapsable();
$isWrapped = $containerId || $element->getHeaderBar() || $isCollapsable;
$titleActions = '<div class="actions">' . $element->getHeaderBar() . '</div>';
$isField = $element->getFieldsetType() == 'field';
$advancedAfter = $element->getAdvancedPosition() == 'after'; // To place advanced options inside or after fieldset
$advancedLabel = $element->getAdvancedLabel();
if (!isset($advancedLabel)) {
    $advancedLabel = __('Additional Settings');
}

$cssClass = ($isField) ? 'field ' . $element->getClass() : 'fieldset admin__fieldset ' . $element->getClass();

if ($isField) {
    $count = $element->getCountBasicChildren();
    $cssClass .= ($element->hasAdvanced()) ? ' complex' : '';
}
?>

<?php
/**
* @todo investigate situations, when the following is needed:
* echo $element->getHeaderBar();
* echo $element->getSubFieldsetHtml();
*/ ?>
<div class="row">
    <div class="col-md-12">
        <div class="<?php echo $cssClass?>">
            <?php if ($element->getLegend()): ?>
            <div class="box-header with-border">
                <i class="fa fa-bars"></i>
                <h3 class="box-title"><?php /* @escapeNotVerified */ echo $element->getLegend() ?></h3>
                <!-- 
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                </div>
                 -->
            </div><!-- /.box-header -->
            <?php endif;?>
            <div class="fieldset admin__fieldset">
                <div class="messages">
                    <?php if ($element->getComment() && !$isField): ?>
                        <div class="message message-notice"><?php echo $block->escapeHtml($element->getComment()) ?></div>
                    <?php endif; ?>
                </div>
                <?php if ($element->hasHtmlContent() && !$isField): ?>
                    <?php echo $element->getHtmlContent(); ?>
                <?php else: ?>
                    <?php echo $element->getBasicChildrenHtml(); ?>
                <?php endif;?>
            </div>
        </div><!-- /.box-body -->
    </div>
</div>