<?php

?>
<script type="text/javascript">
require.config({
	"paths": {
        "Magento_Catalog/js/components/import-handler": "Lof_MarketPlace/js/components/import-handler",
        "Magento_Catalog/js/components/new-category":"Lof_MarketPlace/js/components/new-category",
        "Magento_Catalog/js/components/messages":"Lof_MarketPlace/js/components/messages",
        "Magento_Catalog/js/components/attribute-set-select":"Lof_MarketPlace/js/components/attribute-set-select",
        "Magento_Catalog/js/components/dynamic-rows-import-custom-options":"Lof_MarketPlace/js/components/dynamic-rows-import-custom-options",
        "Magento_Catalog/js/components/dynamic-rows-tier-price":"Lof_MarketPlace/js/components/dynamic-rows-tier-price",
        "Magento_Catalog/js/components/custom-options-component":"Lof_MarketPlace/js/components/custom-options-component",
        "Magento_Catalog/template/form/field":"Lof_MarketPlace/template/form/field",
        "Magento_Catalog/component/file-type-field.js":"Lof_MarketPlace/component/file-type-field.js",
        "Magento_Catalog/component/select-type-grid.js":"Lof_MarketPlace/component/select-type-grid.js",
        "Magento_Catalog/component/static-type-container.js":"Lof_MarketPlace/component/static-type-container.js",
        "Magento_Catalog/component/static-type-input.js":"Lof_MarketPlace/component/static-type-input.js",
        "Magento_Catalog/component/static-type-select.js":"Lof_MarketPlace/component/static-type-select.js",
        "Magento_Catalog/component/text-type-field.js":"Lof_MarketPlace/component/text-type-field.js",
        "Magento_Catalog/js/custom-options-type.js":"Lof_MarketPlace/js/custom-options-type.js",
        "Magento_Catalog/js/bundle-proxy-button":"Lof_MarketPlace/js/bundle-proxy-button",
        "Magento_CatalogInventory/js/components/use-config-settings":"Lof_MarketPlace/js/components/use-config-settings",
        "Magento_CatalogInventory/js/components/qty-validator-changer":"Lof_MarketPlace/js/components/qty-validator-changer",
        "Magento_CatalogInventory/js/components/use-config-min-sale-qty":"Lof_MarketPlace/js/components/use-config-min-sale-qty",
        "Magento_Catalog/js/bundle-proxy-button":"Lof_MarketPlace/js/bundle-proxy-button",
        "Magento_ConfigurableProduct/js/components/price-configurable":"Lof_MarketPlace/js/components/price-configurable",
        "Magento_Bundle/js/components/bundle-dynamic-rows":"Lof_MarketPlace/js/components/bundle-dynamic-rows",
        "Magento_Bundle/js/components/bundle-dynamic-rows-grid":"Lof_MarketPlace/js/components/bundle-dynamic-rows-grid",
        "Magento_Bundle/js/components/bundle-checkbox":"Lof_MarketPlace/js/components/bundle-checkbox",
        "Magento_Bundle/js/components/bundle-record":"Lof_MarketPlace/js/components/bundle-record",
        "Magento_Bundle/js/components/bundle-option-qty":"Lof_MarketPlace/js/components/bundle-option-qty",
        "productGallery":"Lof_MarketPlace/js/product-gallery",
        "baseImage":"Lof_MarketPlace/catalog/base-image-uploader",
        "Magento_Backend/js/media-uploader":"Lof_MarketPlace/js/media-uploader",
        "Magento_Variable/variables":"Lof_MarketPlace/js/components/variables",
        "Magento_Customer/js/section-config":"Lof_MarketPlace/js/section-config",
        "Magento_Customer/js/customer-data":"Lof_MarketPlace/js/customer-data",
        "Magento_Theme/js/view/messages":"Lof_MarketPlace/js/view/messages"

	}
});
</script>
